In [1]:

import requests
import pandas as pd
import numpy as np
from snowflake.connector.pandas_tools import pd_writer
from snowflake.connector.pandas_tools import write_pandas
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

c:\Users\ShatthikBarua\AppData\Local\Programs\Python\Python310\lib\site-packages\snowflake\connector\options.py:96: UserWarning: You have an incompatible version of 'pyarrow' installed (9.0.0), please install a version that adheres to: 'pyarrow<8.1.0,>=8.0.0; extra == "pandas"'
  warn_incompatible_dep(

In [2]:
engine = create_engine(URL(
        account = 'QCOHCUV-MM41421',
        user = 'SHATTHIK',
        password = 'Shattiker1',
        database = 'TRADE',
        schema = 'FLOW',
        warehouse = 'COMPUTE_WH'
    ))

In [3]:
col_formats={
'Counterparty':str,
'Execution Broker BIC':str,
'Broker Name':str,
'Settlement location':str,
'PSET':str,
'Agent BIC':str,
'Entity BIC':str,
'Entity Name':str,
'Securities Account Number':str,
'Local code':str,
'Clearing code':str,
'DTC':int,
'Institutional ID':int,
'Agent Bank ID':int}

In [4]:
SSI = pd.read_excel(r"G:\Shared drives\Norselab - Investment Team\Norselab AS\13 Projects\High Yield\Operational set-up\All_Counterparties_bonds_SSIs.xlsx",converters=col_formats)

In [5]:
SSI.columns = [i.upper().replace(" ","_") for i in SSI.columns]

In [6]:
SSI

,COUNTERPARTY,EXECUTION_BROKER_BIC,BROKER_NAME,SETTLEMENT_LOCATION,PSET,AGENT_BIC,ENTITY_BIC,ENTITY_NAME,SECURITIES_ACCOUNT_NUMBER,LOCAL_CODE,CLEARING_CODE,DTC,INSTITUTIONAL_ID,AGENT_BANK_ID
0,ABG,ABSRNOK1,ABG Sundal Collier,NO,VPSNNOKK,ABSRNOK1,ABSRNOK1,ABG Sundal Collier,NaN,11830,NaN,NaN,NaN,NaN
1,ABG,ABSRNOK1,ABG Sundal Collier,SE,VPCSSESS,ASNFSES1,ASNFSES1,ABG Sundal Collier,NaN,ABC,NaN,NaN,NaN,NaN
2,ABG,ABSRNOK1,ABG Sundal Collier,DK,VPDKDKKKXXX,ABSRNOK1XXX,ABSRNOK1XXX,ABG Sundal Collier,NaN,13031,NaN,NaN,NaN,NaN
3,ABG,ABSRNOK1,ABG Sundal Collier,FI,APKEFIHHXXX,ESSEFIHXXXX,ABSRNOK1XXX,ABG Sundal Collier,10-100 149 260,NaN,NaN,NaN,NaN,NaN
4,ABG,ABSRNOK1,ABG Sundal Collier,EU,CEDELULL,NaN,CITIGB2L,Citibank N.A. London Branch,NaN,14319,CEDE,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,SEB,NaN,NaN,SE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,SEB,NaN,NaN,DK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,SEB,NaN,NaN,FI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,SEB,NaN,NaN,EU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,SEB,NaN,NaN,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#SSI.SECURITIES_ACCOUNT_NUMBER = SSI.SECURITIES_ACCOUNT_NUMBER.astype(str)
#SSI.LOCAL_CODE = SSI.LOCAL_CODE.astype(str)

In [8]:
SSI.to_sql("ssi",con = engine,if_exists="replace",index=False,method=pd_writer)

In [9]:
######FX#########

col_formats={
'Counterparty':str,
'Broker BIC':str,
'Broker Name':str,
'Currency':str,
'Local Agent BIC':str,
'Entity Name':str}

SSI_FX = pd.read_excel(r"G:\Shared drives\Norselab - Investment Team\Norselab AS\13 Projects\High Yield\Operational set-up\All_Counterparties_FX_SSIs.xlsx",converters=col_formats)

In [10]:
SSI_FX.columns = [i.upper().replace(" ","_") for i in SSI_FX.columns]

In [11]:
SSI_FX

,COUNTERPARTY,BROKER_BIC,BROKER_NAME,CURRENCY,LOCAL_AGENT_BIC,ENTITY_NAME
0,DNB,DNBANOKX,DNB Markets,NOK,DNBANOKX,DNB Bank ASA
1,DNB,DNBANOKX,DNB Markets,SEK,DNBASESX,DNB Bank ASA
2,DNB,DNBANOKX,DNB Markets,DKK,DNBADKKX,DNB Bank ASA
3,DNB,DNBANOKX,DNB Markets,EUR,DNBANOKX,DNB Bank ASA
4,DNB,DNBANOKX,DNB Markets,USD,DNBAUS33,DNB Bank ASA
5,RBC,FETALULL,RBC Investor Services SA,NOK,DNBANOKX,DNB Bank ASA
6,RBC,FETALULL,RBC Investor Services SA,SEK,DNBASESX,DNB Bank ASA
7,RBC,FETALULL,RBC Investor Services SA,DKK,DNBADKKX,DNB Bank ASA
8,RBC,FETALULL,RBC Investor Services SA,EUR,FETALULL,RBC Investor Services SA
9,RBC,FETALULL,RBC Investor Services SA,USD,DNBAUS33,DNB Bank ASA
10,NORD,NDEANOKK,"Nordea Bank Abp, filial i Norge",NOK,NDEANOKK,"Nordea Bank Abp, filial i Norge"
11,NORD,NDEANOKK,"Nordea Bank Abp, filial i Norge",SEK,NDEASESS,"Nordea Bank Abp, filial i Sverige"
12,NORD,NDEANOKK,"Nordea Bank Abp, filial i Norge",DKK,NDEADKKK,"Nordea Denmark, filial af Nordea Bank Abp, Fin..."
13,NORD,NDEANOKK,"Nordea Bank Abp, filial i Norge",EUR,NDEAFIHH,Nordea Bank Abp
14,NORD,NDEANOKK,"Nordea Bank Abp, filial i Norge",USD,BOFAUS3N,Bank of America
15,DAN,DABADKKK,Danske Bank AS,NOK,DABANO22,Danske Bank AS
16,DAN,DABADKKK,Danske Bank AS,SEK,DABASESX,Danske Bank
17,DAN,DABADKKK,Danske Bank AS,DKK,DABADKKK,Danske Bank AS
18,DAN,DABADKKK,Danske Bank AS,EUR,DABADKKK,Danske Bank AS
19,DAN,DABADKKK,Danske Bank AS,USD,BOFAUS3N,Bank of America

In [12]:
SSI_FX.to_sql("ssi_fx",con = engine,if_exists="replace",index=False,method=pd_writer)

In [15]:
SSI.COUNTERPARTY.unique()

array(['ABG', 'FEA', 'ARC', 'SB1', 'CLA', 'CAR', 'PAR', 'DAN', 'NORD',
       'DNB', 'SEB'], dtype=object)